architecture: ksevendet
backbone: resnet 

# Default Support Variant
variant: resnet18
#variant: resnet26
#variant: resnet26d
#variant: resnet34
#variant: resnet50
#variant: resnet50d
#variant: resnet101
#variant: resnet152

# Specifical Build Config
#build_config: {}
# following config is an example for shufflenetv2
backbone_config: {
    stages_repeats: [4, 8, 4],
    stages_out_channels: [24, 116, 232, 464, 1024],
}

#neck: fpn
#neck: panet-fpn
neck: bifpn
neck_config: {
    #features_num: 64,
    #features_num: 128,
    features_num: 128,
    bifpn_repeats: 1,
    bifpn_attention: False,
}

head_config: {
    #head_type:    'efficient',
    #act_type:     'swish',
    features_num: 128,
    #features_num: 256,
    layers_num  : 3,

    conv_kernel_size : 3,
    conv_stride      : 1,
    conv_padding     : 1,
}

backbone_feature_pyramid_levels : [3, 4, 5]
neck_feature_pyramid_levels     : [3, 4, 5, 6, 7]

anchors_config: {
    sizes_mapper : 'lambda level: 2**(level + 2)',
    #sizes_mapper : 'lambda level: 2**(level + 1) * 1.25',
    ratios : [1, 2],
    scales : '[2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]',
}
