architecture: ksevendet
backbone: efficientnet

# Default Support Variant
variant: efficientnet_b0
#variant: efficientnet_b1
#variant: efficientnet_b2
#variant: efficientnet_b2a
#variant: efficientnet_b3
#variant: efficientnet_b3a
#variant: efficientnet_b4
#variant: efficientnet_b5
#variant: efficientnet_b6
#variant: efficientnet_b7
#variant: efficientnet_b8
#variant: efficientnet_lite0
#variant: efficientnet_lite1
#variant: efficientnet_lite2
#variant: efficientnet_lite3
#variant: efficientnet_lite4
#variant: efficientnet_

# Specifical Build Config
#build_config: {}
# following config is an example for shufflenetv2
backbone_config: {
    stages_repeats: [4, 8, 4],
    stages_out_channels: [24, 116, 232, 464, 1024],
}

#neck: fpn
#neck: panet-fpn
neck: bifpn
neck_config: {
    bifpn_repeats: 3,
    bifpn_attention: False,
}

fpn_features_num : 64
#fpn_features_num : 128
#fpn_features_num : 256
backbone_feature_pyramid_levels : [3, 4, 5]
neck_feature_pyramid_levels     : [3, 4, 5, 6, 7]
