architecture: ksevendet
backbone: sknet

# Default Support Variant
variant: skresnet18
#variant: skresnet34
#variant: skresnet50
#variant: skresnet50d
#variant: skresnext50_32x4d

# Specifical Build Config
#build_config: {}
# following config is an example for shufflenetv2
backbone_config: {
    stages_repeats: [4, 8, 4],
    stages_out_channels: [24, 116, 232, 464, 1024],
}

#neck: fpn
#neck: panet-fpn
neck: bifpn
neck_config: {
    bifpn_repeats: 2,
    bifpn_attention: False,
}

fpn_features_num : 64
#fpn_features_num : 128
#fpn_features_num : 256
backbone_feature_pyramid_levels : [3, 4, 5]
neck_feature_pyramid_levels     : [3, 4, 5, 6, 7]
